repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.4.0
    hooks:
      - id: validate_manifest

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
    -   id: ruff
    